### ISSUE TITLE
etcd is being slippery today, missing etcd.env post push

### ISSUE THREAD

**Issue by fuag15** [steveeJ/personal-portage-overlay#4]
Calculating dependencies  ... done!

> > > Verifying ebuild manifests

!!! A file listed in the Manifest could not be found: /var/lib/layman/steveeJ/dev-db/etcd/files/etcd.env
INFO[0109] The command [/bin/sh -c layman -a steveeJ && emerge =dev-db/etcd-2.0.9] returned a non-zero code: 1

**Comment by steveej** [comment]
That should work. Please synchronize the overlay again.

**Comment by fuag15** [comment]
your right! sorry. I must have hit layman at an odd time. reran and it worked. Thanks again for the quick fixes today!
